local Parser=require("chat_parser")

test("parses room speech target and verb",function()
  local e=assert(Parser.parse('Ocinaiya says to Suupidosutaa, "Especially you."',"Dace Alterac","2026-08-31T13:00:00-04:00"))
  eq(e.schema,1); eq(e.timestamp,"2026-08-31T13:00:00-04:00"); eq(e.character,"Dace Alterac")
  eq(e.category,"ROOM"); eq(e.speaker,"Ocinaiya"); eq(e.target,"Suupidosutaa"); eq(e.message,"Especially you.")
  eq(e.line,'Ocinaiya says to Suupidosutaa, "Especially you."'); eq(e.source,"builtin")
end)

test("parses room speech languages and all approved verbs",function()
  local asks=assert(Parser.parse('Ocinaiya asks in Elvish to Suupidosutaa, "Are you ready?"',"Dace Alterac"))
  eq(asks.category,"ROOM"); eq(asks.target,"Suupidosutaa"); eq(asks.language,"Elvish")
  for _,verb in ipairs({"exclaims","shouts","yells"}) do
    eq(assert(Parser.parse('Ocinaiya '..verb..' in Common, "Hello!"')).category,"ROOM")
  end
end)

test("parses active character speech and unquoted own output",function()
  local spoken=assert(Parser.parse('Dace Alterac says, "I am here."',"Dace Alterac"))
  eq(spoken.category,"OWN"); eq(spoken.speaker,"Dace Alterac"); eq(spoken.message,"I am here.")
  local e=assert(Parser.parse("You say I'm new.","Dace Alterac"))
  eq(e.category,"OWN"); eq(e.speaker,"Dace Alterac"); eq(e.message,"I'm new.")
  eq(e.target,nil); eq(e.language,nil)
end)

test("parses incoming and outgoing whispers",function()
  local incoming=assert(Parser.parse('Ocinaiya whispers to you, "Keep this quiet."',"Dace Alterac"))
  eq(incoming.category,"WHISPER"); eq(incoming.speaker,"Ocinaiya"); eq(incoming.target,"Dace Alterac")
  local outgoing=assert(Parser.parse('You whisper to Ocinaiya, "I will."',"Dace Alterac"))
  eq(outgoing.category,"WHISPER"); eq(outgoing.speaker,"Dace Alterac"); eq(outgoing.target,"Ocinaiya")
end)

test("parses private mental and staff channels",function()
  local esp=assert(Parser.parse('Tekk (ESP): "ahhh and she returns"'))
  eq(esp.category,"ESP"); eq(esp.speaker,"Tekk"); eq(esp.message,"ahhh and she returns")
  local dragon=assert(Parser.parse('You pick up Losmir\'s mental link, "dragon door... is unlocked"'))
  eq(dragon.category,"DRAGON"); eq(dragon.speaker,"Losmir"); eq(dragon.message,"dragon door... is unlocked")
  local contact=assert(Parser.parse('You pick up Faolann\'s thoughts echoing through the area, "leave me be"'))
  eq(contact.category,"CONTACT"); eq(contact.speaker,"Faolann"); eq(contact.message,"leave me be")
  eq(assert(Parser.parse('Aerin (ELDER): "Please remain calm."')).category,"STAFF")
  eq(assert(Parser.parse('[GUIDE] Aerin: Follow the northern road.')).category,"STAFF")
end)

test("normalizes ANSI before parsing",function()
  local e=assert(Parser.parse('\27[31mTekk\27[0m (ESP): "ahhh and she returns"'))
  eq(e.speaker,"Tekk"); eq(e.line,'Tekk (ESP): "ahhh and she returns"')
end)

test("rejects malformed empty and misleading narration",function()
  eq(Parser.parse("The teller whispers to you about opening an account."),nil)
  eq(Parser.parse('Ocinaiya says, Especially you.'),nil)
  eq(Parser.parse('Ocinaiya says, "Especially you.'),nil)
  eq(Parser.parse('Ocinaiya says, ""'),nil)
  eq(Parser.parse('Tekk (ESP): "   "'),nil)
  eq(Parser.parse('[GUIDE] Aerin:   '),nil)
end)

test("validates safe custom categories and preserves supplied metadata",function()
  eq(Parser.category(" quest-log "),"QUEST-LOG")
  eq(Parser.category("QUEST_LOG"),"QUEST_LOG")
  eq(Parser.category("quest log"),nil)
  eq(Parser.category("QUEST!"),nil)
  local entry=assert(Parser.custom(" quest-log ","The invasion has started.",{
    speaker="Herald",target="Dace Alterac",language="Common",timestamp="2026-08-31T13:00:00-04:00",line="Herald announces the invasion.",
  },"Dace Alterac","2026-08-31T12:00:00-04:00"))
  eq(entry.schema,1); eq(entry.timestamp,"2026-08-31T13:00:00-04:00"); eq(entry.character,"Dace Alterac")
  eq(entry.category,"QUEST-LOG"); eq(entry.speaker,"Herald"); eq(entry.target,"Dace Alterac"); eq(entry.language,"Common")
  eq(entry.message,"The invasion has started."); eq(entry.line,"Herald announces the invasion."); eq(entry.source,"custom")
  eq(Parser.custom("bad category!","hello"),nil)
  eq(Parser.custom("QUEST","   "),nil)
end)
