local History=require("chat_history")

test("deduplicates only identical adjacent entries",function()
  local history=History.new(1000,3)
  local entry={category="ESP",speaker="Tekk",message="hello"}
  eq(history:append(entry,100),true)
  eq(history:append(entry,101),false)
  eq(history:append({category="ESP",speaker="Gia",message="hello"},102),true)
  eq(history:append(entry,103),true)
end)

test("retains only the newest visible limit",function()
  local history=History.new(2,3)
  history:append({category="ROOM",message="one"},1)
  history:append({category="ROOM",message="two"},2)
  history:append({category="ROOM",message="three"},3)
  eq(#history:entries("ALL"),2)
  eq(history:entries("ALL")[1].message,"two")
end)

test("filters private categories and preserves category insertion order",function()
  local history=History.new(10,3)
  history:append({category="ROOM",message="room"},1)
  history:append({category="WHISPER",message="whisper"},2)
  history:append({category="ESP",message="esp"},3)
  history:append({category="DRAGON",message="dragon"},4)
  history:append({category="CONTACT",message="contact"},5)
  history:append({category="STAFF",message="staff"},6)
  eq(#history:entries("PRIVATE"),4)
  eq(history:entries("PRIVATE")[1].message,"whisper")
  local categories=history:categories()
  eq(categories[1],"ROOM")
  eq(categories[6],"STAFF")
end)
