local Layout=require("layout")
test("wide screens reserve seventeen percent for each HUD rail",function()
  local r=Layout.compute(1920,1080); eq(r.mode,"wide"); eq(r.left,326); eq(r.right,326); eq(r.console_width,1268); eq(r.header_height,74); eq(r.show_character_rail,true); eq(r.vitals_side,"left")
end)
test("chatbox aligns exactly with center console",function()
  local r=Layout.compute(1920,1080)
  eq(r.chat_x,r.left); eq(r.chat_width,r.console_width); eq(r.chat_height,240)
  eq(r.console_top,r.header_height+r.chat_height); eq(r.top,r.console_top)
end)
test("chat height scales and clamps",function()
  eq(Layout.compute(1200,650).chat_height>=160,true)
  eq(Layout.compute(3840,2160).chat_height<=320,true)
end)
test("chat allocation preserves a usable console remainder at medium and compact thresholds",function()
  for _,case in ipairs({{width=1200,header=66},{width=760,header=116}}) do
    local threshold=case.header+160+120
    local above=Layout.compute(case.width,threshold+1); local at=Layout.compute(case.width,threshold); local below=Layout.compute(case.width,threshold-1)
    eq(at.minimum_console_remainder,120)
    eq(above.chat_height,160); eq(above.console_remainder,121)
    eq(at.chat_height,160); eq(at.console_remainder,120)
    eq(below.chat_height,159); eq(below.console_remainder,120)
    eq(below.chat_height>0,true); eq(below.console_top<below.window_height,true)
  end
end)
test("short medium and compact layouts keep chat visible above the console remainder",function()
  local medium=Layout.compute(1200,200); local compact=Layout.compute(760,240)
  eq(medium.chat_height,60); eq(medium.chat_output_height,16); eq(medium.console_remainder,74)
  eq(compact.chat_height,60); eq(compact.chat_output_height,16); eq(compact.console_remainder,64)
  eq(medium.console_remainder>0,true); eq(compact.console_remainder>0,true)
  eq(medium.console_top<=medium.window_height,true); eq(compact.console_top<=compact.window_height,true)
end)
test("functional chat chrome floor adapts the console minimum at medium and compact boundaries",function()
  for _,case in ipairs({{width=1200,header=66},{width=760,header=116}}) do
    local threshold=case.header+60+120
    local above=Layout.compute(case.width,threshold+1); local at=Layout.compute(case.width,threshold); local below=Layout.compute(case.width,threshold-1)
    eq(at.chat_functional_minimum,60); eq(at.chat_height,60); eq(at.chat_output_height,16); eq(at.console_remainder,120)
    eq(above.chat_height,61); eq(above.chat_output_height,17); eq(above.console_remainder,120)
    eq(below.chat_height,60); eq(below.chat_output_height,16); eq(below.console_remainder,119)
    eq(below.console_remainder>0,true)
  end
end)
test("extreme compact height compresses header before chat or console overrun",function()
  local r=Layout.compute(760,150)
  eq(r.header_height,89); eq(r.chat_height,60); eq(r.chat_output_height,16); eq(r.console_remainder,1)
  eq(r.console_top<=r.window_height,true)
end)
test("normal layouts retain their breakpoint headers and chat geometry",function()
  local compact=Layout.compute(760,700); local medium=Layout.compute(1200,800); local wide=Layout.compute(1920,1080)
  eq(compact.header_height,116); eq(compact.chat_height,160)
  eq(medium.header_height,66); eq(medium.chat_height,178)
  eq(wide.header_height,74); eq(wide.chat_height,240)
end)
test("chat wrap columns follow the center display width",function()
  local narrow=Layout.compute(1000,700); local wide=Layout.compute(1920,1080)
  eq(narrow.chat_wrap_columns<wide.chat_wrap_columns,true); eq(narrow.chat_wrap_columns>=30,true)
end)
test("chat text scales slightly smaller than the surrounding HUD",function()
  eq(Layout.compute(760,700).chat_font,11)
  eq(Layout.compute(1920,1080).chat_font,13)
  eq(Layout.compute(3840,2160).chat_font,15)
end)
test("chat height follows supplied percentage while retaining reference target",function()
  local default=Layout.compute(1920,1080); local taller=Layout.compute(1920,1080,{height_percent=.25})
  eq(default.chat_height,240); eq(taller.chat_height>default.chat_height,true)
end)
test("medium screens preserve the seventeen sixty-six seventeen split",function()
  local r=Layout.compute(1200,800); eq(r.mode,"medium"); eq(r.left,204); eq(r.right,204); eq(r.console_width,792); eq(r.header_height,66); eq(r.show_character_rail,true); eq(r.show_room_compass,true); eq(r.vitals_side,"left")
end)
test("compact screens move all status out of side rails",function()
  local r=Layout.compute(760,700); eq(r.mode,"compact"); eq(r.left,0); eq(r.right,0); eq(r.header_height,116); eq(r.bottom,0); eq(r.show_room_compass,false)
end)
test("duplicate bottom information row reserves no console space",function()
  for _,size in ipairs({{760,700},{1200,800},{2560,1400}}) do eq(Layout.compute(size[1],size[2]).bottom,0) end
end)
test("layout leaves sixty-six percent of rail layouts for the main console",function()
  for _,w in ipairs({1000,1024,1366,1400,1600,1920,2056,2560,3840}) do local r=Layout.compute(w,900); eq(r.console_width>=w*.66,true) end
end)
test("responsive typography remains readable at every breakpoint",function()
  local compact=Layout.compute(760,700); local medium=Layout.compute(1200,800); local wide=Layout.compute(2056,1177); local ultra=Layout.compute(3840,2160)
  eq(compact.body_font>=16,true); eq(medium.body_font>=16,true); eq(wide.body_font>=20,true); eq(ultra.body_font>=22,true)
  eq(wide.heading_font>wide.body_font,true); eq(wide.gauge_height>=26,true); eq(wide.panel_padding>=16,true)
  eq(wide.small_font>=(wide.body_font-2)*2,true); eq(wide.gauge_height>=wide.small_font+10,true)
end)
test("component metrics grow without overflowing narrow layouts",function()
  for _,size in ipairs({{760,700},{900,650},{1200,800},{2056,1177},{3840,2160}}) do
    local r=Layout.compute(size[1],size[2]); eq(r.body_font<=22,true); eq(r.heading_font<=28,true); eq(r.panel_padding<=24,true); eq(r.gauge_height<=56,true)
  end
end)

test("content boxes scale with typography instead of clipping",function()
  local compact=Layout.compute(760,700); local wide=Layout.compute(1920,1080)
  eq(wide.title_height>=wide.heading_font+24,true)
  eq(wide.status_height>=wide.body_font*4+32,true)
  eq(wide.room_height>=wide.heading_font+wide.body_font*6+44,true)
  eq(wide.exit_height>=wide.small_font+12,true)
  eq(wide.status_height>compact.status_height,true)
  eq(wide.identity_height>=wide.heading_font+wide.body_font*6+48,true)
end)

test("new cards derive dimensions from responsive fonts",function()
  for _,size in ipairs({{760,700},{1200,800},{2056,1177},{3840,2160}}) do
    local r=Layout.compute(size[1],size[2]); eq(r.inventory_row_height>=r.inventory_font+8,true); eq(r.details_line_height>=r.body_font+4,true); eq(r.compass_cell>=r.compass_font+10,true); eq(r.utility_height>=r.utility_font+10,true); eq(r.console_width>=size[1]*.66,true)
  end
end)
test("character details move to the roomier rail when the left stack is short",function()
  eq(Layout.detailsPlacement(240,26,500),"left")
  eq(Layout.detailsPlacement(240,26,300),"right")
  eq(Layout.detailsPlacement(180,26,500),"right")
  eq(Layout.detailsPlacement(120,26,500),"right")
end)
test("two-column character details reserve every rendered row",function()
  eq(Layout.detailsCardRows(2),11)
  eq(Layout.detailsCardRows(4),7)
end)
test("right rail preserves minimum inventory before showing character details",function()
  eq(Layout.detailsFit(900,400,240,140),true)
  eq(Layout.detailsFit(700,400,240,140),false)
end)
test("lower-left vitals stack uses compact readable gauge typography",function()
  local r=Layout.compute(1920,1080)
  eq(r.lower_scale,.8)
  eq(r.lower_title_height,0)
  eq(r.lower_small_font<=r.lower_body_font+1,true)
  eq(r.lower_gauge_height>=r.lower_small_font+12,true)
  for _,pair in ipairs({
    {r.lower_body_font,r.body_font},{r.lower_heading_font,r.heading_font},
    {r.lower_panel_padding,r.panel_padding},{r.lower_row_gap,r.row_gap},
    {r.lower_status_height,r.status_height},{r.lower_room_height,r.room_height},{r.lower_compass_cell,r.compass_cell},
    {r.lower_utility_height,r.utility_height}
  }) do eq(pair[1],math.floor(pair[2]*.8+.5)) end
end)
test("embedded mapper is allocated immediately above compass on wide screens",function()
  local r=Layout.compute(1920,1080)
  eq(r.mapper_visible,true); eq(r.lower_mapper_height>=140,true)
  eq(r.lower_mapper_gap,r.lower_row_gap)
end)
test("medium and short windows preserve mapper before optional room detail",function()
  for _,size in ipairs({{1200,800},{1200,650},{1000,650}}) do
    local r=Layout.compute(size[1],size[2])
    eq(r.mapper_visible,true); eq(r.lower_mapper_height>=90,true)
    eq(r.lower_room_visible_height<=r.lower_room_height,true)
  end
end)
test("compact layouts may hide the embedded mapper",function()
  local r=Layout.compute(760,700)
  eq(r.mapper_visible,false); eq(r.lower_mapper_height,0)
end)
test("lower panel reduction preserves location and mapper floors before hiding the mapper",function()
  local wide=Layout.compute(2560,1400); local full=Layout.lowerPanelGeometry(wide,true,true)
  eq(full.optional_count,2); eq(full.room_height,wide.lower_room_height); eq(full.mapper_height>=140,true)
  local medium=Layout.compute(1200,650); local constrained=Layout.lowerPanelGeometry(medium,true,true)
  eq(constrained.optional_count<2,true)
  eq(constrained.room_height>=medium.lower_room_min_height,true)
  if constrained.mapper_height>0 then eq(constrained.mapper_height>=90,true) end
  local impossible=Layout.compute(1200,420); local reduced=Layout.lowerPanelGeometry(impossible,true,true)
  eq(reduced.mapper_height,0)
  eq(reduced.panel_height<=impossible.window_height-impossible.header_height,true)
end)
