local Navigation=require("navigation")
test("normalizes abbreviated and full compass directions",function()
  local a=Navigation.availability({"north","NE","e","southwest","up"}); eq(a.north,true); eq(a.northeast,true); eq(a.east,true); eq(a.southwest,true); eq(a.south,false); eq(a.up,nil)
end)
test("defines exact utility commands",function()
  eq(Navigation.utilities[1].label,"GO PORTAL"); eq(Navigation.utilities[1].command,"go portal"); eq(Navigation.utilities[2].command,"go door"); eq(Navigation.utilities[3].command,"go gate"); eq(Navigation.utilities[4].command,"go arch")
end)
test("places all eight directions around an empty center",function()
  eq(#Navigation.directions,8); local occupied={}; for _,d in ipairs(Navigation.directions) do occupied[d.row..":"..d.col]=true end; eq(occupied["2:2"],nil); eq(occupied["1:1"],true); eq(occupied["3:3"],true)
end)
