local Layout=require("layout")
test("wide screens reserve full command deck rails",function()
  local r=Layout.compute(1920,1080); eq(r.mode,"wide"); eq(r.left,326); eq(r.right,288); eq(r.top,74); eq(r.show_character_rail,true); eq(r.vitals_side,"left")
end)
test("medium screens preserve console by folding character rail",function()
  local r=Layout.compute(1200,800); eq(r.mode,"medium"); eq(r.left,228); eq(r.right,203); eq(r.top,66); eq(r.show_character_rail,true); eq(r.show_room_compass,true); eq(r.vitals_side,"left")
end)
test("compact screens move all status out of side rails",function()
  local r=Layout.compute(760,700); eq(r.mode,"compact"); eq(r.left,0); eq(r.right,0); eq(r.top,116); eq(r.bottom,58); eq(r.show_room_compass,false)
end)
test("layout always leaves most of the window for the main console",function()
  for _,w in ipairs({1000,1024,1366,1400,1600,1920,2056,2560,3840}) do local r=Layout.compute(w,900); eq((w-r.left-r.right)>=w*.64,true) end
end)
test("responsive typography remains readable at every breakpoint",function()
  local compact=Layout.compute(760,700); local medium=Layout.compute(1200,800); local wide=Layout.compute(2056,1177); local ultra=Layout.compute(3840,2160)
  eq(compact.body_font>=16,true); eq(medium.body_font>=16,true); eq(wide.body_font>=20,true); eq(ultra.body_font>=22,true)
  eq(wide.heading_font>wide.body_font,true); eq(wide.gauge_height>=26,true); eq(wide.panel_padding>=16,true)
  eq(wide.small_font>=(wide.body_font-2)*2,true); eq(wide.gauge_height>=wide.small_font+10,true); eq(wide.bottom>=wide.small_font+16,true)
end)
test("component metrics grow without overflowing narrow layouts",function()
  for _,size in ipairs({{760,700},{900,650},{1200,800},{2056,1177},{3840,2160}}) do
    local r=Layout.compute(size[1],size[2]); eq(r.body_font<=22,true); eq(r.heading_font<=28,true); eq(r.panel_padding<=24,true); eq(r.gauge_height<=56,true)
  end
end)

test("content boxes scale with typography instead of clipping",function()
  local compact=Layout.compute(760,700); local wide=Layout.compute(1920,1080)
  eq(wide.title_height>=wide.heading_font+24,true)
  eq(wide.status_height>=wide.body_font*4+32,true)
  eq(wide.room_height>=wide.heading_font+wide.body_font*6+44,true)
  eq(wide.exit_height>=wide.small_font+12,true)
  eq(wide.status_height>compact.status_height,true)
  eq(wide.identity_height>=wide.heading_font+wide.body_font*4+48,true)
end)

test("new cards derive dimensions from responsive fonts",function()
  for _,size in ipairs({{760,700},{1200,800},{2056,1177},{3840,2160}}) do
    local r=Layout.compute(size[1],size[2]); eq(r.inventory_row_height>=r.inventory_font+8,true); eq(r.details_line_height>=r.body_font+4,true); eq(r.compass_cell>=r.compass_font+10,true); eq(r.utility_height>=r.utility_font+10,true); eq((size[1]-r.left-r.right)>=size[1]*.64,true)
  end
end)
test("character details move to the roomier rail when the left stack is short",function()
  eq(Layout.detailsPlacement(240,26),"left")
  eq(Layout.detailsPlacement(180,26),"right")
  eq(Layout.detailsPlacement(120,26),"right")
end)
test("two-column character details reserve every rendered row",function()
  eq(Layout.detailsCardRows(2),11)
  eq(Layout.detailsCardRows(4),7)
end)
